---
title: "Problem Set 2"
author: "Denits Panova, Thomas Vicente ,Felix Gutmann"
date: "15 May 2016"
output: pdf_document
---

### Problem 1

## a)

***(1)***

Define the utilities as:
$$
\begin{aligned}
U_i(A) &:= \alpha + d_i^Aa \\
U_i(B) &:= \beta + d_i^Bb, 
\end{aligned}
$$
where $\alpha$, $\beta$ $\ge$ $0$ and $d_i^*a$ is the number ...

Best reply:
$$
\begin{aligned}
U_i(A) > U_i(B)
\end{aligned}
$$
Substitute the definition of the utilities in the last equation:
$$
\begin{aligned}
\alpha + d_i^Aa > \beta + d_i^Bb
\end{aligned}
$$
Define $d_i$ and rephrase it:
$$
\begin{aligned}
d_i := d_i^A + d_i^B \\
\underbrace{\frac{d_i^A}{d_i}}_{f_i} + \underbrace{\frac{d_i^B}{d_i}}_{(1-f_i)} = 1 
\end{aligned}
$$
Using the last identity we can write the the inequality in the following way:
$$
\begin{aligned}
\alpha + f_ia > \beta +(1-f_i) b \\
f_i(a+b) \ge  \beta + b - \alpha \\
f_i \ge \frac{(\beta - \alpha) + b}{b+a} \in [0,1]
\end{aligned}
$$
Let $p_A=\frac{(\beta - \alpha) + b}{b+a}$ and $p_B=(1-p_A)=\frac{(\alpha - \beta) + a}{b+a}$. So best response is to choose A **iff** at least $p_A$ of its friends chhose A. 

***(b)***

The Nash-Equilibrium (NE) appears when:

* any node i that chooses A has at least $p_A$ friends who also choose A
* any node i that chooses B has at least $p_B$ friend who also choose B

***(c)***

Let $C_p$ a p-cluster and $C_p \subset G$. In the p-clustering sense we can say that NE occurs if i chooses A then $i \in C_A$, where $C_A$ is a $p_A$-cluster and if i chooses B  then $i \in C_B$, where $C_B$ is a $p_B$-cluster. 

## b)

Set $\alpha=\beta=0$. Each nodes starts with B. Let $t=q=\frac{1}{2}$ for switching to A. 

***(b1)***

Let $S=\{e-f\}$, where S is the starting set meaning that the two nodes initially adopt behaviour A. 

!!!!! FOR FELIX !!!!!! put in a graph or leave some space for drawing one #Denisisthebest 

***(b2)***

The Blocking set is $BS:=\{ g,j \}$, with density $D=\frac{2}{3}$. 

## c) 

!!!! DENI WILL PAINT SOME MORE STUFF!!!

## d)

No we can't have the same Nash-Equilibria, because when we have a tie we are more likely to choose one of them namely to choose the one which has bigger initial values ($\alpha$ or $\beta$). 

### Problem 2

***(2.1.a)***

Step 1:
$h_{A_i}^{(1)}=2h_{C_i}^{(1)}=\frac{1}{8}$
$a_{B_i}^{(1)}=\frac{3}{8}$ 
$a_{D}^{(1)}=\frac{5}{8}$ 
Step 2:
$h_{A_i}^{(2)}=\frac{9}{8}$
$a_{B_i}^{(2)}=\frac{27}{8}$ 
$h_{C_i}^{(2)}=\frac{5}{8}$
$a_{D}^{(2)}=\frac{25}{8}$ 
Conclusion:
$a_{B_i}^{(2)}>a_{D}^{(2)}$ 
even from the second iteration there is a difference between the authority meassures of the two different nodes. 
***(2.1.b)***

We define the formulas for the two sub-graphs separatly. The first sub-graph consists of A's and B's. Let $b:=\text{number of B's}$ and $a:=\text{number of A's}$ and $c=\text{constant}=\frac{1}{8}$. For
Step $k=1$: 
$h^{(1)}=a^0b^0c = c$
$a^{(1)}=ab^0c$
Step $k=2$: 
$h^{(2)}=a^{(1)}b =bab^0c = b^{(k-1)}a^{(k-1)}c$
$a^{(2)}=abab^0c=a^{(k)}b^{(k-1)}c$
Step $k=3$: 
$h^{(3)}=a^{(2)}b = a^{(k-1)}b^{(k-2)}bc = a^{(k-1)}b^{(k-1)}bc$
$a^{(3)}=aa^{(k-1)}b^{(k-1)}c=a^{(k)}b^{(k-1)}c$
In general we define:
$h_{A_i}^{(k)}:=a^{(k-1)}b^{(k-1)}bc$
$a_{B_i}^{(k)}:=a^{(k)}b^{(k-1)}c$

for the secon sub-graph 
Step $k=1$: 
$h^{(1)}= c$
$a^{(1)}=5c$
Step $k=2$: 
$h^{(2)}=5c=5^{(k-1)}c$
$a^{(2)}=5*5c=5^{k}c$
In general we define:
$h_{C_i}^{(k)}=5^{(k-1)}c$
$a_{D}^{(k)}=5^{k}c$

***(2.1.c)***

Let the normalizing constant be 
$$
\begin{aligned}
const_h&=3[a^{k-1}b^{k-1}c] +5 5^{k-1}c \\
&=3 3^{2k-2} c + 5^{k}c \\
&=(3^{2k-1}+5^k)c
\end{aligned}
$$
The normalized version of the hub meassure is:
$$
\begin{aligned}
\widehat{h_{A_i}}&=\frac{h_{A_i}}{const_h} \\
&\propto \frac{9^k}{(3^{2k-1}+5^k)}
\widehat{h_{C_i}} = \frac{5^k}{3^{2k-1}k+5^k}
\end{aligned}
$$
The other authority nomalizing constant is define as:
$$
\begin{aligned}
const_{a} = 3 a^{K}b^{k-1} c + 5^{k} c \\
&= 3^{k} c + 5^{k} c \\
\widehat{a_{B_i}} = \frac{3^{2k-1}}{3^{K}b^{k-1} + 5^{k}  } \\
\propto \frac{9^{K}}{3^{K}+5^{K}} \\
\widehat{a_{D}} = \frac{5^{k}}{3^{K} + 5^{k}}
\end{aligned}
$$
Conclusion: As k goes to infitiy $\widehat{a_{B_i}}$ will go slower to 0 than $\widehat{a_{D}}$. The same is equivalent for $\widehat{h_{A_i}}$ than $\widehat{h_{C_i}}$.
So when pages have multiple reinforcement, meaning hub points to more than one page, then in the world web the authorities will be bigger and could more easily be found. 

***(2.2)***

Than the effect will be the same for the two sub-graph, even it will be accelerated. 

***(2.3)***

SIGNEDSEALEDDELIVERED

```{r}
setwd('/Users/felix/Documents/GSE/Term 3/14D009 Social and Economic Networks/Problemsets/14D009-Social-and-Economic-Networks/')
library(igraph)

#1.2
g <- sample_bipartite(10, 5, p=.4)
gp = bipartite.projection(g)$proj1
H = hub_score(gp)$value
E = eigen_centrality(gp)$value
H ; E
round(H,3) == round(E,3)
round(H,3) == round(E^2,3)



#2.1
probas = c(.01, .1, .25, .6)
for (p in probas) {
	print(paste('For probability =', p, ':'))

	n = 5
	g = erdos.renyi.game(n, p)
	avg = average.path.length(g)

	print(paste('    - average distance =', avg))

	d = get.diameter(g)
	print(paste('    - diameter =', length(d) - 1))

	D <- lower.tri(shortest.paths(g))
	D[D==Inf] <- 0
	print(paste('    - the asbolute difference between the average distance and its approximation is', abs(avg-sum(D)/(n*(n-1))),'.'))
	print(paste('    - the asbolute difference between the diamter and its approximation is', abs(avg-max(D)),'.'))

	d <- degree_distribution(g)
	pdf(paste0('plot_p', p, '.pdf'))
	plot(d, type='l')
	dev.off()

	cl = clusters(g)
	print(paste('    - number of components =', cl$no))

	print('    - we see in the following table:')
	t = table(cl$csize)
	print(t)
	print('')
	print(paste('    that the largest component captures', ifelse(max(as.numeric(rownames(as.matrix((t)))))/n > .8, 'more', 'less'), 'than 80 percent of the nodes.'))
	print('')
	print('')
}



#2.2
d <- read.table('/Users/felix/Documents/GSE/Term 3/14D009 Social and Economic Networks/Problemsets/14D009-Social-and-Economic-Networks/ca-AstroPh.txt', header=T)
a <- graph.adjlist(as.matrix(d))

#centrality measures
a1 = centr_degree
a2 = eigen_centrality
a3 = page_rank
a4 = authority.score

#... their values
a1(a)$centralization
a2(a)$value
a3(a)$value
a4(a)$value

#... and the 10 most central instances according to each of them
c1 = a1(a)$res
c2 = a2(a)$vector
c3 = a3(a)$vector
c4 = a4(a)$vector
maxC <- function(v) {unlist(as.matrix(sort.int(v, decreasing=T, index.return=TRUE))[2])[1:10]}
print('degree centrality')
maxC(c1)
print('eigen centrality')
maxC(c2)
print('page rank')
maxC(c3)
print('HITS')
maxC(c4)
#id 53213 appears 3 times as the most central one




g <- graph_from_edgelist(as.matrix(d), directed = F)
d <- degree_distribution(g)
plot(d, type='l', ylim=range(0,.01))
n <- 133279
cl <- clusters(g)
print(paste('    - number of components =', cl$no))

print('    - we see in the following table:')
t = table(cl$csize)
print(t)
print('')
print(paste('    that the largest component captures', round(17903/n*100, 0), 'percent of the nodes.'))
print('But this cluster is still much bigger than the second one.')
```


